name: shelf_simple_session
version: 0.1.3
author: Warren Strange <warren.strange@gmail.com>
description: A simple session manager for shelf middleware
homepage: https://github.com/wstrange/shelf_simple_session
environment:
  sdk: '>=1.5.0 <2.0.0'
dependencies:
  crypto: ^2.0.0
  cryptoutils: ^0.3.0
  logging: '>=0.9.1 <1.0.0'
  shelf: '>=0.5.4 <0.7.0'
